<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function job_listing_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the login_module module.
    case 'help.page.job_listing':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is used for Job Listing API') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_theme().
 */
function job_listing_theme() {
  return [
    'job_listing' => [
      'variables' => [
        'jobs' => NULL,
      ]
      ],
  ];
}
